baseURL: "https://rohitgoswami.in/"
languageCode: en-us
title: mr-roh
theme: PaperMod

publishDir: docs

params:
    profileMode:
        enabled: false
        title: "<Title>" # optional default will be site title
        subtitle: "Just getting started!!"
        imageUrl: "https://avatars.githubusercontent.com/u/15854015?s=400&u=495bac6c286a88cdeda9afb7794bef4ecee4fb9f&v=4" # optional
        imageTitle: "mr-roh" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/rohit-goswami"

    socialIcons: # optional
        - name: twitter
          url: "https://twitter.com/mrroh_in"

params:
  homeInfoParams:
    Title: Hi there!
    Content: Welcome to mr-roh's blog.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/mrroh_in"
    - name: github
      url: "https://github.com/"


params:
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

params:
    assets:
        disableFingerprinting: true
        
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30


footer:
  block: minimal
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  # For multilingual sites, show a language chooser in the footer?
  show_translations: true